-- New script in LOCAL.
-- Date: 29 de dez. de 2022
-- Time: 15:52:09
-- By Analista Wesley
-- CONNECTION: name=LOCAL
-- New script in LOCAL.
-- Date: 2 de dez. de 2022
-- Time: 13:56:57
-- By Wesley
--CREATE OR ALTER VIEW V_TIME_PA_SCMI_889 (
--PRONT,NOME,NOME_SIG,REG,STATUS,"LOCAL",TEMPO,ID_TBFLUXOATEND,ID_TBSENHAATEND
--)
--AS 
WITH CURRENT_STATUS	AS (


	SELECT
		DISTINCT
		-- TBFLUXOATEND.ID_TBSENHAATEND,
		MAX(TBFLUXOATEND.ID) OVER ( PARTITION BY TBFLUXOATEND.ID_TBSENHAATEND
	ORDER BY
		TBFLUXOATEND.DATA_HORA DESC )CURRENT_ID_FLUXO
	FROM
		TBFLUXOATEND 
),

 CURRENT_PRESC AS ( 

SELECT --- PRESCRICAO/RECENTE PACIENTE DIA
HTATENDIMENTO.ID_ATCABECATEND, 
HTPACIENTE.NOME AS NOME,
HTPACIENTE.ID AS HTPACIENTE_ID , 
--PRPRESC.ID, 
MAX(PRPRESC.ID) MAXID --- SEMPRE A PRESCRICAO MAIS RECENTE
FROM PRPRESC PRPRESC
INNER JOIN PRLANGERAL PRLANGERAL ON PRPRESC.ID =  PRLANGERAL.ID_PRPRESC
INNER JOIN HTPACIENTE  HTPACIENTE ON HTPACIENTE.ID  = PRPRESC.ID_HTPACIENTE
INNER JOIN HTATENDIMENTO HTATENDIMENTO ON HTATENDIMENTO.ID = PRPRESC.ID_HTATENDIMENTO
INNER JOIN RECADATE RECADATE ON RECADATE.ID_ATCABECATEND  =HTATENDIMENTO.ID_ATCABECATEND 
INNER JOIN TBCLINICA TBCLINICA ON TBCLINICA.COD = HTATENDIMENTO.ID_TBCLINICA
WHERE
(
TBCLINICA.COD = 'S'
		OR
RECADATE.CDC = 20)
AND
PRPRESC.DATA_HORA_PRESCRICAO >= (CURRENT_DATE  ) || ' 00:01:01.000'
AND 
PRPRESC.JUSTIFICATIVA_SUSPENSAO IS NULL
GROUP BY 
 1,2,3

)


SELECT DISTINCT 
CURRENT_PRESC.*

FROM 
CURRENT_PRESC
JOIN ATCABECATEND_TBSENHAATEND ON ATCABECATEND_TBSENHAATEND.ID_ATCABECATEND  = CURRENT_PRESC.ID_ATCABECATEND
JOIN TBFLUXOATEND TBFLUXOATEND ON TBFLUXOATEND.ID_TBSENHAATEND =  ATCABECATEND_TBSENHAATEND.ID_TBSENHAATEND 
