-- CONNECTION: name=LOCAL
-- New script in LOCAL.
-- Date: 2 de dez. de 2022
-- Time: 13:56:57
-- By Wesley

SELECT DISTINCT 

(  SELECT FIRST 1 RICADPAC.PRONT  FROM RICADPAC WHERE RICADPAC.PRONT  =RECADATE.PRONT  )  PRONT, 
(  SELECT FIRST 1 RICADPAC.NOME  FROM RICADPAC WHERE RICADPAC.PRONT  =RECADATE.PRONT  ) NOME,
(  SELECT FIRST 1  
substring(RICADPAC.NOME from 1 for position(' ', RICADPAC.NOME)) || '  ' || iif(position(' ', RICADPAC.NOME) + 1 > 1,
 substring(RICADPAC.NOME from position(' ', RICADPAC.NOME) + 1 for 1), '') /*segunda*/ || iif(position(' ', RICADPAC.NOME,
 position(' ', RICADPAC.NOME) + 1) + 1 > 2, substring(RICADPAC.NOME from position(' ', RICADPAC.NOME, position(' ', RICADPAC.NOME) + 1) + 1 for 1), '')
 /*terceira*/ || iif(position(' ', RICADPAC.NOME, position(' ', RICADPAC.NOME, position(' ', RICADPAC.NOME) + 1) + 1) + 1 > 3,
 substring(RICADPAC.NOME from position(' ', RICADPAC.NOME, position(' ', RICADPAC.NOME, position(' ', RICADPAC.NOME) + 1) + 1) + 1 for 1), '')FROM RICADPAC WHERE RICADPAC.PRONT  =RECADATE.PRONT  )CLIENTE,
( SELECT FIRST 1 ATCABECATEND.COD_ATENDIMENTO  FROM ATCABECATEND WHERE HTATENDIMENTO.ID_ATCABECATEND = ATCABECATEND.ID) REG,

CASE TBFLUXOATEND.ACAO 
     WHEN   'C' THEN 'CHAMADO'
     WHEN   'X' THEN 'REENVIO DE CHAMADA'
     WHEN   'C' THEN 'CHAMADO'
     WHEN   'A' THEN 'ATENDIMENTO'
     WHEN   'L' THEN 'LIBERADO'
     WHEN   'E' THEN 'ENCAMINHADO'
     ELSE 
      TBFLUXOATEND.ACAO
END STATUS,
TBLOCAL.DESCRICAO AS LOCAL,
CAST(  /*VERIFICA DIAS*/
                (CASE DATEDIFF(DAY FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP)
                 WHEN 0
                 /* MENOS DE 24 HORAS*/
                 THEN ''
                 ELSE
                 /* DIAS COMPLETOS*/
                 DATEDIFF(DAY FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP) || 'D'
                 END
                 ) ||
                /*VERIFICA HORAS*/
                (CASE
                /*MENOS DE 60*/
                 WHEN 
                 TRUNC(
                 CAST(
                 DATEDIFF(
                 MINUTE FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP) AS NUMERIC(9,2)) / 60
                 ) < 60
                    THEN
                 TRUNC(
                 CAST(
                 DATEDIFF(
                 MINUTE FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP) AS NUMERIC(9,2)) / 60)
                        ELSE
                        /*MAIS DE 1 MINUTO - EXTRAI AS HORAS COMPLETAS DEIXANDO APENAS MINUTOS*/
                        TRUNC(TRUNC(CAST(DATEDIFF(MINUTE FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP) AS NUMERIC(9,2)) / 60) -
                            (DATEDIFF(DAY FROM TBSENHAATEND.DATA_HORA TO CURRENT_TIMESTAMP) * 24))
               END)
            || 'h' ||
            /*EXTRAI OS MINUTOS*/
            MOD(CAST(DATEDIFF(MINUTE FROM TBSENHAATEND.DATA_HORA  TO CURRENT_TIMESTAMP) AS NUMERIC(9,2)), 60)
                || 'm' AS VARCHAR(50)) TEMPO ,
TBFLUXOATEND.*


FROM 

  

(

SELECT
DISTINCT 
-- TBFLUXOATEND.ID_TBSENHAATEND,
MAX(TBFLUXOATEND.ID) OVER ( PARTITION BY TBFLUXOATEND.ID_TBSENHAATEND ORDER BY TBFLUXOATEND.DATA_HORA DESC )I 
FROM 
TBFLUXOATEND 
) FLUXO
JOIN TBFLUXOATEND ON TBFLUXOATEND.ID =FLUXO.I 
JOIN TBSENHAATEND ON TBFLUXOATEND.ID_TBSENHAATEND = TBSENHAATEND.ID
JOIN ATCABECATEND_TBSENHAATEND ON ATCABECATEND_TBSENHAATEND.ID_TBSENHAATEND = TBSENHAATEND.ID 
JOIN RECADATE ON RECADATE.ID_ATCABECATEND = ATCABECATEND_TBSENHAATEND.ID_ATCABECATEND 
JOIN HTATENDIMENTO HTATENDIMENTO ON HTATENDIMENTO.ID_ATCABECATEND = ATCABECATEND_TBSENHAATEND.ID_ATCABECATEND
JOIN ATCABECATEND ON HTATENDIMENTO.ID_ATCABECATEND  = ATCABECATEND.ID 
JOIN TBCLINICA TBCLINICA ON TBCLINICA.COD = HTATENDIMENTO.ID_TBCLINICA 
JOIN TBLOCAL ON TBFLUXOATEND.ID_TBLOCAL = TBLOCAL.ID 
WHERE 
TBFLUXOATEND.ACAO NOT SIMILAR TO 'L'
AND 
ATCABECATEND.DATA_HORA_ENTRADA >= (CURRENT_DATE) || ' 00:01:01.000'
AND 
 (
TBCLINICA.COD = 'S'
OR
RECADATE.CDC = 20)
ORDER BY 
TBFLUXOATEND.ID DESC 








